feature: thrust now able to boot traits
revosystems/thrust pull request #142
Opened 2024-10-22 11:17 UTC by kiriamcf-revo

Això fa el mateix que Laravel amb el boot dels traits. 

Podeu mirar el construct de: [source](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Model.php)

Aixo ens permet fer refactor de traits de thrust perquè no tinguin conflictes al sobre-escriure creates / deletes.

Un exemple és aqui (li falta canvis al composer per afegir la versio de thrust am aquest boot):

2024-10-22 12:28 UTC, MartiSalaMorral approved these changes

2024-10-22 12:58 UTC, PauBenetPrat approved these changes

2024-10-22 13:30 UTC, BadChoice commented on src/Resource.php
> +    public function __construct() {
podem posar tot aixo en un Trait BootableResource, aquesta classe es mostruosa ja..

2024-10-23 07:36 UTC, kiriamcf-revo commented on src/Resource.php
> +    public function __construct() {
Fet!

2024-10-24 15:22 UTC, alexrevo requested changes

2024-10-24 15:22 UTC, alexrevo commented on src/Concerns/BootableResource.php
> +    public function __construct() {
no és bona pràctica posar un constructor a dins d'un TRAIT

2024-10-24 18:06 UTC, kiriamcf-revo commented on src/Concerns/BootableResource.php
> +    public function __construct() {
Doncs trec el construct a fora del trait? Té sentit tenir el trait després? O ho deixo com estava abans del canvi que va demanar el @BadChoice?

2024-10-25 06:30 UTC, BadChoice commented on src/Concerns/BootableResource.php
> +    public function __construct() {
aquest trait es un 1..1 per tant jo crec que pots fer que el pare faci el $this->parentId... i no caldra que facis el construct

2024-10-25 08:16 UTC, kiriamcf-revo commented on src/Concerns/BootableResource.php
> +    public function __construct() {
No t'acabo de pillar, que té a veure el parentId amb el construct i tota la lògica del trait?

2024-10-29 08:46 UTC, BadChoice approved these changes

2024-10-29 08:47 UTC, BadChoice commented
no em deixa fer merge, diria que per el request changes de l'edu

2024-10-29 08:48 UTC, draude commented
> no em deixa fer merge, diria que per el request changes de l'edu

És de l'Alex @alexrevo 🙄

2024-10-29 15:27 UTC, alexrevo approved these changes

2024-10-29 15:27 UTC, merged