REV-11882
revosystems/thrust pull request #66
Opened 2023-06-22 13:55 UTC by MartiSalaMorral

Added context to child resoruce's edit
Added displayWhileSearching property to field
https://linear.app/revo/issue/REV-11882/versio-thurst

2023-06-27 15:00 UTC, BadChoice requested changes

2023-06-27 15:00 UTC, BadChoice commented on src/Fields/Field.php
> +    public $showWhileSearching = false;
jo mantindria la coherencia, showInSearch

2023-06-28 06:22 UTC, MartiSalaMorral commented on src/Html/Index.php
> +            return $field->showInIndex || request('search') && $field->showWhileSearching;
No entec la proposta. Vols dir així?
`return $field->showInIndex
      || request('search') && $field->showWhileSearching;`

2023-06-28 09:23 UTC, BadChoice approved these changes

2023-06-28 09:24 UTC, merged